language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - .autoconf
env:
  matrix:
    - TEST_SET="-Ptravis_main"
    - TEST_SET="-Ptravis_e2e"

install: true

script:
  - bash travis.sh $TEST_SET