language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - .autoconf
    - $HOME/.m2
env:
  matrix:
    - TEST_SET=clean install -Ptravis_main
    - TEST_SET=clean install -Ptravis_e2e

install: true

script:
  - bash travis.sh $TEST_SET