language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - .autoconf
    - $HOME/.m2

install: true

matrix:
  - TEST_SET=clean install -Ptravis_main
  - TEST_SET=clean install -Ptravis_e2e

script:
  - bash travis.sh $TEST_SET