sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - .autoconf
env:
  matrix:
    - TEST_SET="-Ptravis_e2e_skip"
    - TEST_SET="-Ptravis_e2e"
    - TEST_SET="-fn -Ptravis_e2e_no_fail"

install: true

script:
  - bash travis.sh $TEST_SET